site_name: Isekai'd Documentation
theme: 
  name: 'material'
  logo: assets/logo.png
  favicon:
    'images/favicon.ico'
  features:
    - navigation.tabs
    - navigation.instant
    - content.tabs.link


  palette:
    scheme: slate
    primary: 'lime'
    accent: 'Violet'
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  

extra_css: 
  - stylesheet/style.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      alternate_style: true 
nav: 
  - Home: 
    - Home: index.md
    - Table of contents: SUMMARY.md
    - FAQ: FAQ.md
  - Getting Started: 
    - Getting Started: getting-started/getting-started.md
    - Subclasses: getting-started/subclasses.md
  - Trade: trade/trade.md
  - Battles:
    - Battling: battles/battle.md
    - Equipment: battles/equipment.md
    - Skills: battles/skills.md
  - Fishing: fishing/fishing.md
  - Guilds: guilds/guilds.md
  - Pets: pets/pets.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NixDevs
      name: ARLO#5097 
   
      
